#cloud-config
hostname: $VM_NAME
fqdn: $FQDN
preserve_hostname: false
manage_etc_hosts: true
users:
  - name: picta
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/picta
    shell: /bin/bash
    lock_passwd: false
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCZ7WJwtCO9tXG+xuBtYH5AEWaOEwWSdUN/S36c7sg6sE2eFAK7TQZxkxM5tyyLcyRDZcbQTYAGKH+GtqbjwmT6hYfE0Gz4+FpN98/enBldJmQbutRS9pFKF7iEgxuuLuRDFXlyIjh4ATVPttyQKDS6H+m4swI5ZAlRFRPgwCXrfM7EecUs8V1JzioMZOXH0maopECf7YI9H91QHMA7mcerQPx8rCvzs0wSQpxS4qwuAYC8TEFt3cv6VI+i+5DXP2opPeehbJOarAvM9TW1eaSXCB0Xlb+nm/i1ETYpUkngPB9gXZAgaBrKjoVT1dvxiwDDEPe1oJHroJodLVvaxazRLI265bKUDSWNC9hMbojY/hNzn1a0/sV4JVqoDPWa7LzvPhTZUumfbWev/83EHTzpa4GsynYTxsAKwB5HaAEWcZmvVZhIvqMBhGEuKWzYPCFR5tfkFIDboLWLKPqia138U4i3tnmwTmrzkiD3XmhA2gAaiKMg96S9rw1eox6sjdk=
ssh_pwauth: false
disable_root: false
chpasswd:
  list: |
     picta:fuckoff
  expire: False
packages:
  - qemu-guest-agent
  - openssh-server
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg
final_message: "The system is finally up, after $UPTIME seconds"

runcmd:
  - systemctl enable ssh
  - systemctl start ssh
  - sudo modprobe br_netfilter
  - echo "br_netfilter" | sudo tee /etc/modules-load.d/k8s.conf
  - echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf
  - sudo sysctl --system
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - export CRIO_VERSION=v1.34
  - curl -fsSL https://download.opensuse.org/repositories/isv:/cri-o:/stable:/$CRIO_VERSION/deb/Release.key | gpg --dearmor | sudo tee /etc/apt/keyrings/cri-o-apt-keyring.gpg > /dev/null
  - echo "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://download.opensuse.org/repositories/isv:/cri-o:/stable:/$CRIO_VERSION/deb/ /" | sudo tee /etc/apt/sources.list.d/cri-o.list
  - sudo apt-get update
  - sudo apt-get install -y  cri-o
  - sudo systemctl enable --now crio
  - sudo apt-get install -y kubelet kubeadm kubectl
  - MASTER_IP=$(getent hosts k8s-rp.local | awk '{ print $1 }')
  - echo "$MASTER_IP k8s-rp k8s-rp.local" >> /etc/hosts
  - sudo apt install avahi-daemon -y
  - sudo systemctl enable avahi-daemon
  - sudo systemctl start avahi-daemon
  - sudo kubeadm join k8s-rp:6443 --token 3vvb6u.fhp6st4yv5rxkcrq --discovery-token-ca-cert-hash sha256:cf57f5d12d2ae9684464279a4cf605846478eaf10f3e957462ca97bc36bc534c
